services:
  note-vote:
    container_name: note-vote
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    environment:
      MAX_NOTE_LENGTH: 200
      ACCESS_SECRET: secret-id
    volumes:
      - ./data:/app/data
      - ./src/index.html:/app/index.html
      - ./src/app.py:/app/app.py
    restart: unless-stopped
